/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 0;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 1;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 2;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_dbid = new Property();
			pAccount_dbid.name = "dbid";
			pAccount_dbid.properUtype = 2;
			pAccount_dbid.properFlags = 4;
			pAccount_dbid.aliasID = 3;
			Int16 Account_dbid_defval;
			Int16.TryParse("", out Account_dbid_defval);
			pAccount_dbid.defaultVal = Account_dbid_defval;
			pAccountModule.propertys["dbid"] = pAccount_dbid; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_dbid.aliasID] = pAccount_dbid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(dbid / 2).");

			Property pAccount_gameResult = new Property();
			pAccount_gameResult.name = "gameResult";
			pAccount_gameResult.properUtype = 13;
			pAccount_gameResult.properFlags = 16;
			pAccount_gameResult.aliasID = 4;
			Int32 Account_gameResult_defval;
			Int32.TryParse("", out Account_gameResult_defval);
			pAccount_gameResult.defaultVal = Account_gameResult_defval;
			pAccountModule.propertys["gameResult"] = pAccount_gameResult; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_gameResult.aliasID] = pAccount_gameResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(gameResult / 13).");

			Property pAccount_handCards = new Property();
			pAccount_handCards.name = "handCards";
			pAccount_handCards.properUtype = 9;
			pAccount_handCards.properFlags = 16;
			pAccount_handCards.aliasID = 5;
			pAccount_handCards.defaultVal = EntityDef.id2datatypes[28].parseDefaultValStr("");
			pAccountModule.propertys["handCards"] = pAccount_handCards; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_handCards.aliasID] = pAccount_handCards;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(handCards / 9).");

			Property pAccount_handCardsCount = new Property();
			pAccount_handCardsCount.name = "handCardsCount";
			pAccount_handCardsCount.properUtype = 10;
			pAccount_handCardsCount.properFlags = 128;
			pAccount_handCardsCount.aliasID = 6;
			Int32 Account_handCardsCount_defval;
			Int32.TryParse("", out Account_handCardsCount_defval);
			pAccount_handCardsCount.defaultVal = Account_handCardsCount_defval;
			pAccountModule.propertys["handCardsCount"] = pAccount_handCardsCount; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_handCardsCount.aliasID] = pAccount_handCardsCount;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(handCardsCount / 10).");

			Property pAccount_loseCount = new Property();
			pAccount_loseCount.name = "loseCount";
			pAccount_loseCount.properUtype = 6;
			pAccount_loseCount.properFlags = 4;
			pAccount_loseCount.aliasID = 7;
			Int32 Account_loseCount_defval;
			Int32.TryParse("", out Account_loseCount_defval);
			pAccount_loseCount.defaultVal = Account_loseCount_defval;
			pAccountModule.propertys["loseCount"] = pAccount_loseCount; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_loseCount.aliasID] = pAccount_loseCount;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(loseCount / 6).");

			Property pAccount_message = new Property();
			pAccount_message.name = "message";
			pAccount_message.properUtype = 12;
			pAccount_message.properFlags = 4;
			pAccount_message.aliasID = 8;
			Int32 Account_message_defval;
			Int32.TryParse("", out Account_message_defval);
			pAccount_message.defaultVal = Account_message_defval;
			pAccountModule.propertys["message"] = pAccount_message; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_message.aliasID] = pAccount_message;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(message / 12).");

			Property pAccount_modelID = new Property();
			pAccount_modelID.name = "modelID";
			pAccount_modelID.properUtype = 14;
			pAccount_modelID.properFlags = 4;
			pAccount_modelID.aliasID = 9;
			Byte Account_modelID_defval;
			Byte.TryParse("0", out Account_modelID_defval);
			pAccount_modelID.defaultVal = Account_modelID_defval;
			pAccountModule.propertys["modelID"] = pAccount_modelID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_modelID.aliasID] = pAccount_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(modelID / 14).");

			Property pAccount_name = new Property();
			pAccount_name.name = "name";
			pAccount_name.properUtype = 3;
			pAccount_name.properFlags = 32;
			pAccount_name.aliasID = 10;
			string Account_name_defval = "";
			pAccount_name.defaultVal = Account_name_defval;
			pAccountModule.propertys["name"] = pAccount_name; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_name.aliasID] = pAccount_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(name / 3).");

			Property pAccount_nameC = new Property();
			pAccount_nameC.name = "nameC";
			pAccount_nameC.properUtype = 4;
			pAccount_nameC.properFlags = 4;
			pAccount_nameC.aliasID = 11;
			string Account_nameC_defval = "";
			pAccount_nameC.defaultVal = Account_nameC_defval;
			pAccountModule.propertys["nameC"] = pAccount_nameC; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_nameC.aliasID] = pAccount_nameC;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(nameC / 4).");

			Property pAccount_playCards = new Property();
			pAccount_playCards.name = "playCards";
			pAccount_playCards.properUtype = 11;
			pAccount_playCards.properFlags = 4;
			pAccount_playCards.aliasID = 12;
			pAccount_playCards.defaultVal = EntityDef.id2datatypes[29].parseDefaultValStr("");
			pAccountModule.propertys["playCards"] = pAccount_playCards; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playCards.aliasID] = pAccount_playCards;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playCards / 11).");

			Property pAccount_roomKey = new Property();
			pAccount_roomKey.name = "roomKey";
			pAccount_roomKey.properUtype = 1;
			pAccount_roomKey.properFlags = 32;
			pAccount_roomKey.aliasID = 13;
			UInt64 Account_roomKey_defval;
			UInt64.TryParse("", out Account_roomKey_defval);
			pAccount_roomKey.defaultVal = Account_roomKey_defval;
			pAccountModule.propertys["roomKey"] = pAccount_roomKey; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_roomKey.aliasID] = pAccount_roomKey;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(roomKey / 1).");

			Property pAccount_seatIndex = new Property();
			pAccount_seatIndex.name = "seatIndex";
			pAccount_seatIndex.properUtype = 8;
			pAccount_seatIndex.properFlags = 4;
			pAccount_seatIndex.aliasID = 14;
			Int16 Account_seatIndex_defval;
			Int16.TryParse("", out Account_seatIndex_defval);
			pAccount_seatIndex.defaultVal = Account_seatIndex_defval;
			pAccountModule.propertys["seatIndex"] = pAccount_seatIndex; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_seatIndex.aliasID] = pAccount_seatIndex;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(seatIndex / 8).");

			Property pAccount_state = new Property();
			pAccount_state.name = "state";
			pAccount_state.properUtype = 7;
			pAccount_state.properFlags = 32;
			pAccount_state.aliasID = 15;
			Int16 Account_state_defval;
			Int16.TryParse("", out Account_state_defval);
			pAccount_state.defaultVal = Account_state_defval;
			pAccountModule.propertys["state"] = pAccount_state; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_state.aliasID] = pAccount_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(state / 7).");

			Property pAccount_winCount = new Property();
			pAccount_winCount.name = "winCount";
			pAccount_winCount.properUtype = 5;
			pAccount_winCount.properFlags = 4;
			pAccount_winCount.aliasID = 16;
			Int32 Account_winCount_defval;
			Int32.TryParse("", out Account_winCount_defval);
			pAccount_winCount.defaultVal = Account_winCount_defval;
			pAccountModule.propertys["winCount"] = pAccount_winCount; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_winCount.aliasID] = pAccount_winCount;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(winCount / 5).");

			List<DATATYPE_BASE> pAccount_onEnterHall_args = new List<DATATYPE_BASE>();
			pAccount_onEnterHall_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_onEnterHall = new Method();
			pAccount_onEnterHall.name = "onEnterHall";
			pAccount_onEnterHall.methodUtype = 21;
			pAccount_onEnterHall.aliasID = 0;
			pAccount_onEnterHall.args = pAccount_onEnterHall_args;

			pAccountModule.methods["onEnterHall"] = pAccount_onEnterHall; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onEnterHall.aliasID] = pAccount_onEnterHall;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onEnterHall / 21).");

			List<DATATYPE_BASE> pAccount_onEnterSetName_args = new List<DATATYPE_BASE>();
			pAccount_onEnterSetName_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_onEnterSetName = new Method();
			pAccount_onEnterSetName.name = "onEnterSetName";
			pAccount_onEnterSetName.methodUtype = 20;
			pAccount_onEnterSetName.aliasID = 1;
			pAccount_onEnterSetName.args = pAccount_onEnterSetName_args;

			pAccountModule.methods["onEnterSetName"] = pAccount_onEnterSetName; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onEnterSetName.aliasID] = pAccount_onEnterSetName;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onEnterSetName / 20).");

			List<DATATYPE_BASE> pAccount_onReqExitRoom_args = new List<DATATYPE_BASE>();
			pAccount_onReqExitRoom_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_onReqExitRoom = new Method();
			pAccount_onReqExitRoom.name = "onReqExitRoom";
			pAccount_onReqExitRoom.methodUtype = 29;
			pAccount_onReqExitRoom.aliasID = 2;
			pAccount_onReqExitRoom.args = pAccount_onReqExitRoom_args;

			pAccountModule.methods["onReqExitRoom"] = pAccount_onReqExitRoom; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqExitRoom.aliasID] = pAccount_onReqExitRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqExitRoom / 29).");

			List<DATATYPE_BASE> pAccount_onReqJoinRoomFailed_args = new List<DATATYPE_BASE>();
			pAccount_onReqJoinRoomFailed_args.Add(EntityDef.id2datatypes[3]);

			Method pAccount_onReqJoinRoomFailed = new Method();
			pAccount_onReqJoinRoomFailed.name = "onReqJoinRoomFailed";
			pAccount_onReqJoinRoomFailed.methodUtype = 25;
			pAccount_onReqJoinRoomFailed.aliasID = 3;
			pAccount_onReqJoinRoomFailed.args = pAccount_onReqJoinRoomFailed_args;

			pAccountModule.methods["onReqJoinRoomFailed"] = pAccount_onReqJoinRoomFailed; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqJoinRoomFailed.aliasID] = pAccount_onReqJoinRoomFailed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqJoinRoomFailed / 25).");

			List<DATATYPE_BASE> pAccount_onReqJoinRoomSuccess_args = new List<DATATYPE_BASE>();
			pAccount_onReqJoinRoomSuccess_args.Add(EntityDef.id2datatypes[3]);

			Method pAccount_onReqJoinRoomSuccess = new Method();
			pAccount_onReqJoinRoomSuccess.name = "onReqJoinRoomSuccess";
			pAccount_onReqJoinRoomSuccess.methodUtype = 26;
			pAccount_onReqJoinRoomSuccess.aliasID = 4;
			pAccount_onReqJoinRoomSuccess.args = pAccount_onReqJoinRoomSuccess_args;

			pAccountModule.methods["onReqJoinRoomSuccess"] = pAccount_onReqJoinRoomSuccess; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqJoinRoomSuccess.aliasID] = pAccount_onReqJoinRoomSuccess;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqJoinRoomSuccess / 26).");

			List<DATATYPE_BASE> pAccount_onReqPlayersInfo_args = new List<DATATYPE_BASE>();
			pAccount_onReqPlayersInfo_args.Add(EntityDef.id2datatypes[23]);

			Method pAccount_onReqPlayersInfo = new Method();
			pAccount_onReqPlayersInfo.name = "onReqPlayersInfo";
			pAccount_onReqPlayersInfo.methodUtype = 28;
			pAccount_onReqPlayersInfo.aliasID = 5;
			pAccount_onReqPlayersInfo.args = pAccount_onReqPlayersInfo_args;

			pAccountModule.methods["onReqPlayersInfo"] = pAccount_onReqPlayersInfo; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqPlayersInfo.aliasID] = pAccount_onReqPlayersInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqPlayersInfo / 28).");

			List<DATATYPE_BASE> pAccount_onReqRoomPassword_args = new List<DATATYPE_BASE>();
			pAccount_onReqRoomPassword_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_onReqRoomPassword = new Method();
			pAccount_onReqRoomPassword.name = "onReqRoomPassword";
			pAccount_onReqRoomPassword.methodUtype = 27;
			pAccount_onReqRoomPassword.aliasID = 6;
			pAccount_onReqRoomPassword.args = pAccount_onReqRoomPassword_args;

			pAccountModule.methods["onReqRoomPassword"] = pAccount_onReqRoomPassword; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqRoomPassword.aliasID] = pAccount_onReqRoomPassword;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqRoomPassword / 27).");

			List<DATATYPE_BASE> pAccount_onReqRoomsByParams_args = new List<DATATYPE_BASE>();
			pAccount_onReqRoomsByParams_args.Add(EntityDef.id2datatypes[26]);

			Method pAccount_onReqRoomsByParams = new Method();
			pAccount_onReqRoomsByParams.name = "onReqRoomsByParams";
			pAccount_onReqRoomsByParams.methodUtype = 24;
			pAccount_onReqRoomsByParams.aliasID = 7;
			pAccount_onReqRoomsByParams.args = pAccount_onReqRoomsByParams_args;

			pAccountModule.methods["onReqRoomsByParams"] = pAccount_onReqRoomsByParams; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqRoomsByParams.aliasID] = pAccount_onReqRoomsByParams;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqRoomsByParams / 24).");

			List<DATATYPE_BASE> pAccount_onSetNameFailed_args = new List<DATATYPE_BASE>();
			pAccount_onSetNameFailed_args.Add(EntityDef.id2datatypes[3]);
			pAccount_onSetNameFailed_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_onSetNameFailed = new Method();
			pAccount_onSetNameFailed.name = "onSetNameFailed";
			pAccount_onSetNameFailed.methodUtype = 22;
			pAccount_onSetNameFailed.aliasID = 8;
			pAccount_onSetNameFailed.args = pAccount_onSetNameFailed_args;

			pAccountModule.methods["onSetNameFailed"] = pAccount_onSetNameFailed; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onSetNameFailed.aliasID] = pAccount_onSetNameFailed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onSetNameFailed / 22).");

			List<DATATYPE_BASE> pAccount_onSetNameSuccessfully_args = new List<DATATYPE_BASE>();
			pAccount_onSetNameSuccessfully_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_onSetNameSuccessfully = new Method();
			pAccount_onSetNameSuccessfully.name = "onSetNameSuccessfully";
			pAccount_onSetNameSuccessfully.methodUtype = 23;
			pAccount_onSetNameSuccessfully.aliasID = 9;
			pAccount_onSetNameSuccessfully.args = pAccount_onSetNameSuccessfully_args;

			pAccountModule.methods["onSetNameSuccessfully"] = pAccount_onSetNameSuccessfully; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onSetNameSuccessfully.aliasID] = pAccount_onSetNameSuccessfully;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onSetNameSuccessfully / 23).");

			List<DATATYPE_BASE> pAccount_reqCreateRoom_args = new List<DATATYPE_BASE>();
			pAccount_reqCreateRoom_args.Add(EntityDef.id2datatypes[12]);
			pAccount_reqCreateRoom_args.Add(EntityDef.id2datatypes[12]);
			pAccount_reqCreateRoom_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqCreateRoom = new Method();
			pAccount_reqCreateRoom.name = "reqCreateRoom";
			pAccount_reqCreateRoom.methodUtype = 11;
			pAccount_reqCreateRoom.aliasID = -1;
			pAccount_reqCreateRoom.args = pAccount_reqCreateRoom_args;

			pAccountModule.methods["reqCreateRoom"] = pAccount_reqCreateRoom; 
			pAccountModule.base_methods["reqCreateRoom"] = pAccount_reqCreateRoom;

			pAccountModule.idbase_methods[pAccount_reqCreateRoom.methodUtype] = pAccount_reqCreateRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqCreateRoom / 11).");

			List<DATATYPE_BASE> pAccount_reqEditRoomPassword_args = new List<DATATYPE_BASE>();
			pAccount_reqEditRoomPassword_args.Add(EntityDef.id2datatypes[9]);
			pAccount_reqEditRoomPassword_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqEditRoomPassword = new Method();
			pAccount_reqEditRoomPassword.name = "reqEditRoomPassword";
			pAccount_reqEditRoomPassword.methodUtype = 16;
			pAccount_reqEditRoomPassword.aliasID = -1;
			pAccount_reqEditRoomPassword.args = pAccount_reqEditRoomPassword_args;

			pAccountModule.methods["reqEditRoomPassword"] = pAccount_reqEditRoomPassword; 
			pAccountModule.base_methods["reqEditRoomPassword"] = pAccount_reqEditRoomPassword;

			pAccountModule.idbase_methods[pAccount_reqEditRoomPassword.methodUtype] = pAccount_reqEditRoomPassword;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqEditRoomPassword / 16).");

			List<DATATYPE_BASE> pAccount_reqEnterWorld_args = new List<DATATYPE_BASE>();
			pAccount_reqEnterWorld_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqEnterWorld = new Method();
			pAccount_reqEnterWorld.name = "reqEnterWorld";
			pAccount_reqEnterWorld.methodUtype = 14;
			pAccount_reqEnterWorld.aliasID = -1;
			pAccount_reqEnterWorld.args = pAccount_reqEnterWorld_args;

			pAccountModule.methods["reqEnterWorld"] = pAccount_reqEnterWorld; 
			pAccountModule.base_methods["reqEnterWorld"] = pAccount_reqEnterWorld;

			pAccountModule.idbase_methods[pAccount_reqEnterWorld.methodUtype] = pAccount_reqEnterWorld;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqEnterWorld / 14).");

			List<DATATYPE_BASE> pAccount_reqExitGame_args = new List<DATATYPE_BASE>();
			pAccount_reqExitGame_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqExitGame = new Method();
			pAccount_reqExitGame.name = "reqExitGame";
			pAccount_reqExitGame.methodUtype = 19;
			pAccount_reqExitGame.aliasID = -1;
			pAccount_reqExitGame.args = pAccount_reqExitGame_args;

			pAccountModule.methods["reqExitGame"] = pAccount_reqExitGame; 
			pAccountModule.base_methods["reqExitGame"] = pAccount_reqExitGame;

			pAccountModule.idbase_methods[pAccount_reqExitGame.methodUtype] = pAccount_reqExitGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqExitGame / 19).");

			List<DATATYPE_BASE> pAccount_reqExitRoom_args = new List<DATATYPE_BASE>();
			pAccount_reqExitRoom_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqExitRoom = new Method();
			pAccount_reqExitRoom.name = "reqExitRoom";
			pAccount_reqExitRoom.methodUtype = 17;
			pAccount_reqExitRoom.aliasID = -1;
			pAccount_reqExitRoom.args = pAccount_reqExitRoom_args;

			pAccountModule.methods["reqExitRoom"] = pAccount_reqExitRoom; 
			pAccountModule.base_methods["reqExitRoom"] = pAccount_reqExitRoom;

			pAccountModule.idbase_methods[pAccount_reqExitRoom.methodUtype] = pAccount_reqExitRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqExitRoom / 17).");

			List<DATATYPE_BASE> pAccount_reqJoinRoom_args = new List<DATATYPE_BASE>();
			pAccount_reqJoinRoom_args.Add(EntityDef.id2datatypes[9]);
			pAccount_reqJoinRoom_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqJoinRoom = new Method();
			pAccount_reqJoinRoom.name = "reqJoinRoom";
			pAccount_reqJoinRoom.methodUtype = 13;
			pAccount_reqJoinRoom.aliasID = -1;
			pAccount_reqJoinRoom.args = pAccount_reqJoinRoom_args;

			pAccountModule.methods["reqJoinRoom"] = pAccount_reqJoinRoom; 
			pAccountModule.base_methods["reqJoinRoom"] = pAccount_reqJoinRoom;

			pAccountModule.idbase_methods[pAccount_reqJoinRoom.methodUtype] = pAccount_reqJoinRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqJoinRoom / 13).");

			List<DATATYPE_BASE> pAccount_reqPlayGame_args = new List<DATATYPE_BASE>();
			pAccount_reqPlayGame_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqPlayGame = new Method();
			pAccount_reqPlayGame.name = "reqPlayGame";
			pAccount_reqPlayGame.methodUtype = 18;
			pAccount_reqPlayGame.aliasID = -1;
			pAccount_reqPlayGame.args = pAccount_reqPlayGame_args;

			pAccountModule.methods["reqPlayGame"] = pAccount_reqPlayGame; 
			pAccountModule.base_methods["reqPlayGame"] = pAccount_reqPlayGame;

			pAccountModule.idbase_methods[pAccount_reqPlayGame.methodUtype] = pAccount_reqPlayGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqPlayGame / 18).");

			List<DATATYPE_BASE> pAccount_reqRoomPassword_args = new List<DATATYPE_BASE>();
			pAccount_reqRoomPassword_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqRoomPassword = new Method();
			pAccount_reqRoomPassword.name = "reqRoomPassword";
			pAccount_reqRoomPassword.methodUtype = 15;
			pAccount_reqRoomPassword.aliasID = -1;
			pAccount_reqRoomPassword.args = pAccount_reqRoomPassword_args;

			pAccountModule.methods["reqRoomPassword"] = pAccount_reqRoomPassword; 
			pAccountModule.base_methods["reqRoomPassword"] = pAccount_reqRoomPassword;

			pAccountModule.idbase_methods[pAccount_reqRoomPassword.methodUtype] = pAccount_reqRoomPassword;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRoomPassword / 15).");

			List<DATATYPE_BASE> pAccount_reqRoomsByParams_args = new List<DATATYPE_BASE>();
			pAccount_reqRoomsByParams_args.Add(EntityDef.id2datatypes[12]);
			pAccount_reqRoomsByParams_args.Add(EntityDef.id2datatypes[7]);
			pAccount_reqRoomsByParams_args.Add(EntityDef.id2datatypes[7]);
			pAccount_reqRoomsByParams_args.Add(EntityDef.id2datatypes[7]);

			Method pAccount_reqRoomsByParams = new Method();
			pAccount_reqRoomsByParams.name = "reqRoomsByParams";
			pAccount_reqRoomsByParams.methodUtype = 12;
			pAccount_reqRoomsByParams.aliasID = -1;
			pAccount_reqRoomsByParams.args = pAccount_reqRoomsByParams_args;

			pAccountModule.methods["reqRoomsByParams"] = pAccount_reqRoomsByParams; 
			pAccountModule.base_methods["reqRoomsByParams"] = pAccount_reqRoomsByParams;

			pAccountModule.idbase_methods[pAccount_reqRoomsByParams.methodUtype] = pAccount_reqRoomsByParams;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRoomsByParams / 12).");

			List<DATATYPE_BASE> pAccount_reqSetName_args = new List<DATATYPE_BASE>();
			pAccount_reqSetName_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqSetName = new Method();
			pAccount_reqSetName.name = "reqSetName";
			pAccount_reqSetName.methodUtype = 10;
			pAccount_reqSetName.aliasID = -1;
			pAccount_reqSetName.args = pAccount_reqSetName_args;

			pAccountModule.methods["reqSetName"] = pAccount_reqSetName; 
			pAccountModule.base_methods["reqSetName"] = pAccount_reqSetName;

			pAccountModule.idbase_methods[pAccount_reqSetName.methodUtype] = pAccount_reqSetName;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqSetName / 10).");

			List<DATATYPE_BASE> pAccount_callPoint_args = new List<DATATYPE_BASE>();
			pAccount_callPoint_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_callPoint = new Method();
			pAccount_callPoint.name = "callPoint";
			pAccount_callPoint.methodUtype = 6;
			pAccount_callPoint.aliasID = -1;
			pAccount_callPoint.args = pAccount_callPoint_args;

			pAccountModule.methods["callPoint"] = pAccount_callPoint; 
			pAccountModule.cell_methods["callPoint"] = pAccount_callPoint;

			pAccountModule.idcell_methods[pAccount_callPoint.methodUtype] = pAccount_callPoint;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(callPoint / 6).");

			List<DATATYPE_BASE> pAccount_passCards_args = new List<DATATYPE_BASE>();
			pAccount_passCards_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_passCards = new Method();
			pAccount_passCards.name = "passCards";
			pAccount_passCards.methodUtype = 8;
			pAccount_passCards.aliasID = -1;
			pAccount_passCards.args = pAccount_passCards_args;

			pAccountModule.methods["passCards"] = pAccount_passCards; 
			pAccountModule.cell_methods["passCards"] = pAccount_passCards;

			pAccountModule.idcell_methods[pAccount_passCards.methodUtype] = pAccount_passCards;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(passCards / 8).");

			List<DATATYPE_BASE> pAccount_reqAddCard_args = new List<DATATYPE_BASE>();
			pAccount_reqAddCard_args.Add(EntityDef.id2datatypes[8]);
			pAccount_reqAddCard_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_reqAddCard = new Method();
			pAccount_reqAddCard.name = "reqAddCard";
			pAccount_reqAddCard.methodUtype = 9;
			pAccount_reqAddCard.aliasID = -1;
			pAccount_reqAddCard.args = pAccount_reqAddCard_args;

			pAccountModule.methods["reqAddCard"] = pAccount_reqAddCard; 
			pAccountModule.cell_methods["reqAddCard"] = pAccount_reqAddCard;

			pAccountModule.idcell_methods[pAccount_reqAddCard.methodUtype] = pAccount_reqAddCard;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAddCard / 9).");

			List<DATATYPE_BASE> pAccount_reqEditRoomInfo_args = new List<DATATYPE_BASE>();
			pAccount_reqEditRoomInfo_args.Add(EntityDef.id2datatypes[9]);
			pAccount_reqEditRoomInfo_args.Add(EntityDef.id2datatypes[12]);
			pAccount_reqEditRoomInfo_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqEditRoomInfo = new Method();
			pAccount_reqEditRoomInfo.name = "reqEditRoomInfo";
			pAccount_reqEditRoomInfo.methodUtype = 3;
			pAccount_reqEditRoomInfo.aliasID = -1;
			pAccount_reqEditRoomInfo.args = pAccount_reqEditRoomInfo_args;

			pAccountModule.methods["reqEditRoomInfo"] = pAccount_reqEditRoomInfo; 
			pAccountModule.cell_methods["reqEditRoomInfo"] = pAccount_reqEditRoomInfo;

			pAccountModule.idcell_methods[pAccount_reqEditRoomInfo.methodUtype] = pAccount_reqEditRoomInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqEditRoomInfo / 3).");

			List<DATATYPE_BASE> pAccount_reqGameInit_args = new List<DATATYPE_BASE>();
			pAccount_reqGameInit_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqGameInit = new Method();
			pAccount_reqGameInit.name = "reqGameInit";
			pAccount_reqGameInit.methodUtype = 5;
			pAccount_reqGameInit.aliasID = -1;
			pAccount_reqGameInit.args = pAccount_reqGameInit_args;

			pAccountModule.methods["reqGameInit"] = pAccount_reqGameInit; 
			pAccountModule.cell_methods["reqGameInit"] = pAccount_reqGameInit;

			pAccountModule.idcell_methods[pAccount_reqGameInit.methodUtype] = pAccount_reqGameInit;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqGameInit / 5).");

			List<DATATYPE_BASE> pAccount_reqPlayCards_args = new List<DATATYPE_BASE>();
			pAccount_reqPlayCards_args.Add(EntityDef.id2datatypes[30]);

			Method pAccount_reqPlayCards = new Method();
			pAccount_reqPlayCards.name = "reqPlayCards";
			pAccount_reqPlayCards.methodUtype = 7;
			pAccount_reqPlayCards.aliasID = -1;
			pAccount_reqPlayCards.args = pAccount_reqPlayCards_args;

			pAccountModule.methods["reqPlayCards"] = pAccount_reqPlayCards; 
			pAccountModule.cell_methods["reqPlayCards"] = pAccount_reqPlayCards;

			pAccountModule.idcell_methods[pAccount_reqPlayCards.methodUtype] = pAccount_reqPlayCards;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqPlayCards / 7).");

			List<DATATYPE_BASE> pAccount_reqPlayersInfo_args = new List<DATATYPE_BASE>();
			pAccount_reqPlayersInfo_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqPlayersInfo = new Method();
			pAccount_reqPlayersInfo.name = "reqPlayersInfo";
			pAccount_reqPlayersInfo.methodUtype = 4;
			pAccount_reqPlayersInfo.aliasID = -1;
			pAccount_reqPlayersInfo.args = pAccount_reqPlayersInfo_args;

			pAccountModule.methods["reqPlayersInfo"] = pAccount_reqPlayersInfo; 
			pAccountModule.cell_methods["reqPlayersInfo"] = pAccount_reqPlayersInfo;

			pAccountModule.idcell_methods[pAccount_reqPlayersInfo.methodUtype] = pAccount_reqPlayersInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqPlayersInfo / 4).");

			List<DATATYPE_BASE> pAccount_reqReadyPlay_args = new List<DATATYPE_BASE>();
			pAccount_reqReadyPlay_args.Add(EntityDef.id2datatypes[9]);
			pAccount_reqReadyPlay_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_reqReadyPlay = new Method();
			pAccount_reqReadyPlay.name = "reqReadyPlay";
			pAccount_reqReadyPlay.methodUtype = 2;
			pAccount_reqReadyPlay.aliasID = -1;
			pAccount_reqReadyPlay.args = pAccount_reqReadyPlay_args;

			pAccountModule.methods["reqReadyPlay"] = pAccount_reqReadyPlay; 
			pAccountModule.cell_methods["reqReadyPlay"] = pAccount_reqReadyPlay;

			pAccountModule.idcell_methods[pAccount_reqReadyPlay.methodUtype] = pAccount_reqReadyPlay;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqReadyPlay / 2).");

			List<DATATYPE_BASE> pAccount_reqRoomInfo_args = new List<DATATYPE_BASE>();
			pAccount_reqRoomInfo_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_reqRoomInfo = new Method();
			pAccount_reqRoomInfo.name = "reqRoomInfo";
			pAccount_reqRoomInfo.methodUtype = 1;
			pAccount_reqRoomInfo.aliasID = -1;
			pAccount_reqRoomInfo.args = pAccount_reqRoomInfo_args;

			pAccountModule.methods["reqRoomInfo"] = pAccount_reqRoomInfo; 
			pAccountModule.cell_methods["reqRoomInfo"] = pAccount_reqRoomInfo;

			pAccountModule.idcell_methods[pAccount_reqRoomInfo.methodUtype] = pAccount_reqRoomInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRoomInfo / 1).");

			ScriptModule pRoomModule = new ScriptModule("Room");
			EntityDef.moduledefs["Room"] = pRoomModule;
			EntityDef.idmoduledefs[3] = pRoomModule;

			Property pRoom_position = new Property();
			pRoom_position.name = "position";
			pRoom_position.properUtype = 40000;
			pRoom_position.properFlags = 4;
			pRoom_position.aliasID = 0;
			Vector3 Room_position_defval = new Vector3();
			pRoom_position.defaultVal = Room_position_defval;
			pRoomModule.propertys["position"] = pRoom_position; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_position.aliasID] = pRoom_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(position / 40000).");

			Property pRoom_direction = new Property();
			pRoom_direction.name = "direction";
			pRoom_direction.properUtype = 40001;
			pRoom_direction.properFlags = 4;
			pRoom_direction.aliasID = 1;
			Vector3 Room_direction_defval = new Vector3();
			pRoom_direction.defaultVal = Room_direction_defval;
			pRoomModule.propertys["direction"] = pRoom_direction; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_direction.aliasID] = pRoom_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(direction / 40001).");

			Property pRoom_spaceID = new Property();
			pRoom_spaceID.name = "spaceID";
			pRoom_spaceID.properUtype = 40002;
			pRoom_spaceID.properFlags = 16;
			pRoom_spaceID.aliasID = 2;
			UInt32 Room_spaceID_defval;
			UInt32.TryParse("", out Room_spaceID_defval);
			pRoom_spaceID.defaultVal = Room_spaceID_defval;
			pRoomModule.propertys["spaceID"] = pRoom_spaceID; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_spaceID.aliasID] = pRoom_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(spaceID / 40002).");

			Property pRoom_hiddenCards = new Property();
			pRoom_hiddenCards.name = "hiddenCards";
			pRoom_hiddenCards.properUtype = 23;
			pRoom_hiddenCards.properFlags = 16;
			pRoom_hiddenCards.aliasID = 3;
			pRoom_hiddenCards.defaultVal = EntityDef.id2datatypes[31].parseDefaultValStr("");
			pRoomModule.propertys["hiddenCards"] = pRoom_hiddenCards; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_hiddenCards.aliasID] = pRoom_hiddenCards;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(hiddenCards / 23).");

			Property pRoom_hiddenCardsOpen = new Property();
			pRoom_hiddenCardsOpen.name = "hiddenCardsOpen";
			pRoom_hiddenCardsOpen.properUtype = 24;
			pRoom_hiddenCardsOpen.properFlags = 128;
			pRoom_hiddenCardsOpen.aliasID = 4;
			pRoom_hiddenCardsOpen.defaultVal = EntityDef.id2datatypes[32].parseDefaultValStr("");
			pRoomModule.propertys["hiddenCardsOpen"] = pRoom_hiddenCardsOpen; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_hiddenCardsOpen.aliasID] = pRoom_hiddenCardsOpen;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(hiddenCardsOpen / 24).");

			Property pRoom_highestPoint = new Property();
			pRoom_highestPoint.name = "highestPoint";
			pRoom_highestPoint.properUtype = 25;
			pRoom_highestPoint.properFlags = 128;
			pRoom_highestPoint.aliasID = 5;
			Int16 Room_highestPoint_defval;
			Int16.TryParse("", out Room_highestPoint_defval);
			pRoom_highestPoint.defaultVal = Room_highestPoint_defval;
			pRoomModule.propertys["highestPoint"] = pRoom_highestPoint; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_highestPoint.aliasID] = pRoom_highestPoint;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(highestPoint / 25).");

			Property pRoom_intro = new Property();
			pRoom_intro.name = "intro";
			pRoom_intro.properUtype = 18;
			pRoom_intro.properFlags = 128;
			pRoom_intro.aliasID = 6;
			string Room_intro_defval = "";
			pRoom_intro.defaultVal = Room_intro_defval;
			pRoomModule.propertys["intro"] = pRoom_intro; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_intro.aliasID] = pRoom_intro;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(intro / 18).");

			Property pRoom_isGameOver = new Property();
			pRoom_isGameOver.name = "isGameOver";
			pRoom_isGameOver.properUtype = 30;
			pRoom_isGameOver.properFlags = 128;
			pRoom_isGameOver.aliasID = 7;
			Int16 Room_isGameOver_defval;
			Int16.TryParse("", out Room_isGameOver_defval);
			pRoom_isGameOver.defaultVal = Room_isGameOver_defval;
			pRoomModule.propertys["isGameOver"] = pRoom_isGameOver; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_isGameOver.aliasID] = pRoom_isGameOver;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(isGameOver / 30).");

			Property pRoom_isPlaying = new Property();
			pRoom_isPlaying.name = "isPlaying";
			pRoom_isPlaying.properUtype = 19;
			pRoom_isPlaying.properFlags = 128;
			pRoom_isPlaying.aliasID = 8;
			Int16 Room_isPlaying_defval;
			Int16.TryParse("", out Room_isPlaying_defval);
			pRoom_isPlaying.defaultVal = Room_isPlaying_defval;
			pRoomModule.propertys["isPlaying"] = pRoom_isPlaying; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_isPlaying.aliasID] = pRoom_isPlaying;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(isPlaying / 19).");

			Property pRoom_landlordIndex = new Property();
			pRoom_landlordIndex.name = "landlordIndex";
			pRoom_landlordIndex.properUtype = 26;
			pRoom_landlordIndex.properFlags = 128;
			pRoom_landlordIndex.aliasID = 9;
			Int16 Room_landlordIndex_defval;
			Int16.TryParse("", out Room_landlordIndex_defval);
			pRoom_landlordIndex.defaultVal = Room_landlordIndex_defval;
			pRoomModule.propertys["landlordIndex"] = pRoom_landlordIndex; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_landlordIndex.aliasID] = pRoom_landlordIndex;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(landlordIndex / 26).");

			Property pRoom_lastPlayCards = new Property();
			pRoom_lastPlayCards.name = "lastPlayCards";
			pRoom_lastPlayCards.properUtype = 29;
			pRoom_lastPlayCards.properFlags = 128;
			pRoom_lastPlayCards.aliasID = 10;
			pRoom_lastPlayCards.defaultVal = EntityDef.id2datatypes[33].parseDefaultValStr("");
			pRoomModule.propertys["lastPlayCards"] = pRoom_lastPlayCards; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_lastPlayCards.aliasID] = pRoom_lastPlayCards;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(lastPlayCards / 29).");

			Property pRoom_lastPlayIndex = new Property();
			pRoom_lastPlayIndex.name = "lastPlayIndex";
			pRoom_lastPlayIndex.properUtype = 28;
			pRoom_lastPlayIndex.properFlags = 128;
			pRoom_lastPlayIndex.aliasID = 11;
			Int16 Room_lastPlayIndex_defval;
			Int16.TryParse("", out Room_lastPlayIndex_defval);
			pRoom_lastPlayIndex.defaultVal = Room_lastPlayIndex_defval;
			pRoomModule.propertys["lastPlayIndex"] = pRoom_lastPlayIndex; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_lastPlayIndex.aliasID] = pRoom_lastPlayIndex;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(lastPlayIndex / 28).");

			Property pRoom_name = new Property();
			pRoom_name.name = "name";
			pRoom_name.properUtype = 17;
			pRoom_name.properFlags = 128;
			pRoom_name.aliasID = 12;
			string Room_name_defval = "";
			pRoom_name.defaultVal = Room_name_defval;
			pRoomModule.propertys["name"] = pRoom_name; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_name.aliasID] = pRoom_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(name / 17).");

			Property pRoom_openCard = new Property();
			pRoom_openCard.name = "openCard";
			pRoom_openCard.properUtype = 21;
			pRoom_openCard.properFlags = 128;
			pRoom_openCard.aliasID = 13;
			Int16 Room_openCard_defval;
			Int16.TryParse("", out Room_openCard_defval);
			pRoom_openCard.defaultVal = Room_openCard_defval;
			pRoomModule.propertys["openCard"] = pRoom_openCard; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_openCard.aliasID] = pRoom_openCard;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(openCard / 21).");

			Property pRoom_playIndex = new Property();
			pRoom_playIndex.name = "playIndex";
			pRoom_playIndex.properUtype = 27;
			pRoom_playIndex.properFlags = 128;
			pRoom_playIndex.aliasID = 14;
			Int16 Room_playIndex_defval;
			Int16.TryParse("", out Room_playIndex_defval);
			pRoom_playIndex.defaultVal = Room_playIndex_defval;
			pRoomModule.propertys["playIndex"] = pRoom_playIndex; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_playIndex.aliasID] = pRoom_playIndex;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(playIndex / 27).");

			Property pRoom_raiseIndex = new Property();
			pRoom_raiseIndex.name = "raiseIndex";
			pRoom_raiseIndex.properUtype = 22;
			pRoom_raiseIndex.properFlags = 128;
			pRoom_raiseIndex.aliasID = 15;
			Int32 Room_raiseIndex_defval;
			Int32.TryParse("", out Room_raiseIndex_defval);
			pRoom_raiseIndex.defaultVal = Room_raiseIndex_defval;
			pRoomModule.propertys["raiseIndex"] = pRoom_raiseIndex; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_raiseIndex.aliasID] = pRoom_raiseIndex;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(raiseIndex / 22).");

			Property pRoom_roomKey = new Property();
			pRoom_roomKey.name = "roomKey";
			pRoom_roomKey.properUtype = 16;
			pRoom_roomKey.properFlags = 32;
			pRoom_roomKey.aliasID = 16;
			UInt64 Room_roomKey_defval;
			UInt64.TryParse("", out Room_roomKey_defval);
			pRoom_roomKey.defaultVal = Room_roomKey_defval;
			pRoomModule.propertys["roomKey"] = pRoom_roomKey; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_roomKey.aliasID] = pRoom_roomKey;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(roomKey / 16).");

			Property pRoom_seatsData = new Property();
			pRoom_seatsData.name = "seatsData";
			pRoom_seatsData.properUtype = 20;
			pRoom_seatsData.properFlags = 128;
			pRoom_seatsData.aliasID = 17;
			pRoom_seatsData.defaultVal = EntityDef.id2datatypes[23].parseDefaultValStr("");
			pRoomModule.propertys["seatsData"] = pRoom_seatsData; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_seatsData.aliasID] = pRoom_seatsData;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(seatsData / 20).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "UINT8";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "SPACE_KEY";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "UINT32";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ACCOUNT_ID";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "VECTOR3";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "PLAYER_INFOS";
				DATATYPE_PLAYER_INFOS datatype = new DATATYPE_PLAYER_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "SEATS_INFO";
				DATATYPE_SEATS_INFO datatype = new DATATYPE_SEATS_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "ROOM_INFOS";
				DATATYPE_ROOM_INFOS datatype = new DATATYPE_ROOM_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 26;
				string typeName = "ROOM_INFOS_LIST";
				DATATYPE_ROOM_INFOS_LIST datatype = new DATATYPE_ROOM_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 28;
				string typeName = "AnonymousArray_28";
				DATATYPE_AnonymousArray_28 datatype = new DATATYPE_AnonymousArray_28();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 29;
				string typeName = "AnonymousArray_29";
				DATATYPE_AnonymousArray_29 datatype = new DATATYPE_AnonymousArray_29();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 30;
				string typeName = "AnonymousArray_30";
				DATATYPE_AnonymousArray_30 datatype = new DATATYPE_AnonymousArray_30();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 31;
				string typeName = "AnonymousArray_31";
				DATATYPE_AnonymousArray_31 datatype = new DATATYPE_AnonymousArray_31();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 32;
				string typeName = "AnonymousArray_32";
				DATATYPE_AnonymousArray_32 datatype = new DATATYPE_AnonymousArray_32();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 33;
				string typeName = "AnonymousArray_33";
				DATATYPE_AnonymousArray_33 datatype = new DATATYPE_AnonymousArray_33();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}